name: test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: yarn install
    - run: yarn test
      env:
        APP_ID: ${{ secrets.APP_ID }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        WEBHOOK_PROXY_URL: ${{ secrets.WEBHOOK_PROXY_URL }}
